### PR TITLE
Adds global configuration option Model::$short_table_names to allow namespace information to be disregarded when generating table names

### PR DESCRIPTION
**Pull request by michaelward82**
As discussed in PR #90.

### CODE REVIEW

**Comment by treffynnon** [comment]
@Addvilz  I am really busy with other things right now so it will be done as soon as I find the time.

**Comment by DavidePastore** [comment]
+1 :+1:

**Comment by Patabugen** [comment]
This issue is causing a blocker for me in an established project, I'd appreciate a merge as soon as is possible

**Comment by Patabugen** [comment]
Here's a workaround for anyone who needs, it loads @michaelward82 's repo instead of the main one. His appears to be 2 commits behind the official so check whether you need those updates first.

Merge these into your composer.json:
```
{
    "require": {
        "j4mie/paris" : "dev-namespaces as 1.5.x-dev",
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/michaelward82/paris.git"
        }
    ],
    "extra": {
        "branch-alias": {
            "dev-namespaces": "1.5.x-dev"
        }
    }
}
```
More docs here:
https://getcomposer.org/doc/articles/aliases.md
https://getcomposer.org/doc/04-schema.md#repositories

Don't forget to switch back to the main repo if/when this is pulled.

**Comment by michaelward82** [comment]
I've done a pull on my repo to keep it in sync with upstream. The namespaces branch is a non-linear push (forced).

**Comment by treffynnon** [comment]
Sorry peeps I've been in the middle of a lot of life stuff like moving half
way round the world, new job, etc, etc. Service will resume - just not
right now - I don't even have a reliable net connection at the moment!

**Comment by treffynnon** [comment]
Merged into `develop`. Thanks.

**Pull request closed without merging**
